### ISSUE TITLE
Suggestions: Historical Prices 

### ISSUE THREAD

**Issue by dotnetshadow** [lppkarl/YahooFinanceApi#33]
Hi there,
Great Library

**Allow for historical prices to pass in multiple stocks**
It would be nice to be able to pass in a list of stocks for historical prices. Perhaps your api can then loop through the list and make each call (perhaps in parallel)

**Invalid / NotFound**
Firstly I realise you kinda addressed it with #7 
I think from an api point of view, and to be consistent with ` await Yahoo.Symbols`, an error result should be sent back rather than an exception.

**Comment by dshe** [comment]
Thanks for the suggestion.

You can do it yourself, for example:

// start all tasks
var task1 = Yahoo.GetHistoricalAsync(symbol1, ...);
var task2 = Yahoo.GetHistoricalAsync(symbol2, ...);
var task3 = Yahoo.GetHistoricalAsync(symbol3, ...);

// await tasks
var history1 = await task1;
var history2 = await task2;
var history3 = await task3;

**Comment by dshe** [comment]
I suggest you try the new beta version.

**Comment by dotnetshadow** [comment]
Cool ill give it a try, is there support for this now?

**Comment by dshe** [comment]
If a symbol or field is invalid, null is returned instead of an exception being thrown.
