### ISSUE TITLE
'Yahoo' Does not exist in the current context

### ISSUE THREAD

**Issue by pilotkid** [lppkarl/YahooFinanceApi#38]
Hello, I am looking at the sample code and I am seeing a reference to Yahoo. However, when I try to run the samples, I get the error 'Yahoo' Does not exist in the current context. I tried using the classes `YahooQuotes` and `YahooHistory` then I get the error that `Symbols` does not exist in the current context. 

Where are you getting the Yahoo class?

**Comment by dshe** [comment]
Can you please try the 3.0.0-beta3 version:

https://www.nuget.org/packages/YahooFinanceApi/3.0.0-beta3

**Comment by pilotkid** [comment]
That is the version I am running
![image](https://user-images.githubusercontent.com/6385285/61977017-7db7a800-afaa-11e9-937e-16f46a74debc.png)

**Comment by dshe** [comment]
Have a look at this project which uses YahooFinanceApi:

https://github.com/dshe/YahooXL

**Comment by pilotkid** [comment]
Hello, thank you @dshe, this helped immensely. This is what I was looking for.

    var securities = await new YahooQuotes().GetAsync(SymbolsArray);
