### ISSUE TITLE
Error on History data download

### ISSUE THREAD

**Issue by ken88ling** [lppkarl/YahooFinanceApi#7]
It's prompt error if I try to pass invalid ticker of stock

**Comment by ken88ling** [comment]
![capture1](https://user-images.githubusercontent.com/19285908/28219189-aa9e3a2e-68ed-11e7-91af-b32e3f1de5d4.PNG)

Please refer this picture.

**Comment by delvier** [comment]
@ken88ling What you would expect other than 404 (NotFound) when proceeding with invalid ticker ? Is it bad behavior at all ?

**Comment by lppkarl** [comment]
@ken88ling, as @delvier has mentioned, we query by substituing the ticker into the url. If we use an invalid ticker, no valid endpoint can be targeted, hence the 404 error. But i agree that the error message is too generic and does not provide useful information to the failure, I have added an exception message especially for the NotFound error, please see if the changes works for you.

**Comment by ken88ling** [comment]
@delvier @lppkarl  Thank's for your feed back, I don't know why the visual studio is keep warning if I didn't xxx.await(); but after I use the await(), the program will show an error if I give invalid ticker. It's fine if I remove the await().
